"use client";

import Link from "next/link";
import { useEnterpriseData } from "@/lib/enterprise-store";

export default function AdminPage() {
  const { data } = useEnterpriseData();
  return <main className="min-h-screen bg-slate-100 p-6 md:p-10"><div className="mx-auto max-w-6xl"><header className="flex items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Admin</h1><p className="mt-1 text-slate-600">Workspace administration data for the current browser session.</p></div><Link href="/dashboard" className="text-sm font-medium text-blue-700 hover:underline">Dashboard</Link></header><section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Current session</h2>{data.user ? <dl className="mt-4 space-y-3"><div><dt className="text-sm text-slate-500">Name</dt><dd>{data.user.name}</dd></div><div><dt className="text-sm text-slate-500">Email</dt><dd>{data.user.email}</dd></div></dl> : <p className="mt-4 text-slate-600">No user has signed in locally.</p>}</div><div className="rounded-xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Knowledge workspace</h2><p className="mt-4 text-slate-700"><span className="font-semibold">{data.documents.length}</span> documents are registered in this browser.</p><Link href="/upload" className="mt-4 inline-block text-sm font-medium text-blue-700 hover:underline">Manage documents →</Link></div></section><section className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-6 text-amber-900"><h2 className="font-semibold">Backend integration required</h2><p className="mt-2">User roles, connectors, audit logs, and permissions cannot be made real in a frontend-only app. This page intentionally does not show fabricated users, connector states, or audit events.</p></section></div></main>;
}
